apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "devsu-server.fullname" . }}
  labels:
    {{- include "devsu-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "devsu-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "devsu-server.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          envFrom:
          - secretRef:
              name: config
