{{- if .Values.issuer.enabled -}}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Values.issuer.name }}
  labels:
    {{- include "devsu-server.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  acme:
    server: {{ .Values.issuer.server }}
    email: {{ .Values.issuer.email }}
    privateKeySecretRef:
      name: {{ .Values.issuer.name }}
    solvers:
    - http01:
        ingress:
          class: nginx
{{- end }}