apiVersion: v1
kind: Secret
metadata:
  name: config
type: Opaque
data:
  DEVSU_API_KEY: {{ default "" .Values.secret.api_key | b64enc | quote }}
  DEVSU_JWT_KEY: {{ default "" .Values.secret.jwt_key | b64enc | quote }}
